/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.analizadorlexico.ui;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyleContext;
import javax.swing.text.StyledDocument;

/**
 *
 * @author mauricio
 */
public class DialogoBusqueda extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogoBusqueda.class.getName());
    private final String textoFuente;
    public DialogoBusqueda(java.awt.Frame parent, String textoFuente) 
    {
        super(parent, true);
        initComponents();
        this.textoFuente = textoFuente != null ? textoFuente : "";
        txtResultado.setText(this.textoFuente);
        configurarHandlers();
        
    }
    
    private void configurarHandlers() 
    {
        btnBuscar.addActionListener(e -> ejecutarBusqueda());
        txtPalabra.addActionListener(e -> ejecutarBusqueda()); // Enter en campo
    }
    
    private void ejecutarBusqueda() 
    {
        try 
        {
            txtResultado.setText(textoFuente); // restaura texto plano
            String palabra = txtPalabra.getText();
            if (palabra == null || palabra.isEmpty()) return;

            StyledDocument doc = txtResultado.getStyledDocument();
            StyleContext sc = new StyleContext();
            Style estilo = sc.addStyle("resaltado", null);
            StyleConstants.setBackground(estilo, Color.YELLOW);

            char[] texto = textoFuente.toCharArray();
            char[] patron = palabra.toCharArray();
            int n = texto.length, m = patron.length;

            for (int i = 0; i <= n - m; i++) 
            {
                boolean ok = true;
                for (int j = 0; j < m; j++) 
                {
                    if (texto[i + j] != patron[j]) 
                    { 
                        ok = false; 
                        break; 
                    }
                }
                if (ok) doc.setCharacterAttributes(i, m, estilo, false);
            }
        } 
        catch (Exception ex) 
        {
            JOptionPane.showMessageDialog(this, "Error en búsqueda: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPalabra = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Busqueda de Patrones");
        setPreferredSize(new java.awt.Dimension(485, 340));

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText("Palabra exacta: ");
        jPanel1.add(jLabel1);

        txtPalabra.setColumns(20);
        jPanel1.add(txtPalabra);

        btnBuscar.setText("Buscar");
        jPanel1.add(btnBuscar);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        txtResultado.setEditable(false);
        jScrollPane1.setViewportView(txtResultado);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtPalabra;
    private javax.swing.JTextPane txtResultado;
    // End of variables declaration//GEN-END:variables
}
