/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.analizadorlexico.ui;

import javax.swing.JOptionPane;

public class DialogoBusqueda extends javax.swing.JDialog 
{
    public interface BusquedaListener 
    {
        void onBuscar(String patron);
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogoBusqueda.class.getName());
    private BusquedaListener busquedaListener;
    
    public DialogoBusqueda(java.awt.Frame parent, String textoPreseleccionado) 
    {
        super(parent, true);
        initComponents();
        setLocationRelativeTo(parent);
        if (textoPreseleccionado != null && !textoPreseleccionado.isBlank()) 
        {
            txtPalabra.setText(textoPreseleccionado);
            txtPalabra.selectAll();
        }
        configurarHandlers();
    }
    
    public void setBusquedaListener(BusquedaListener listener) 
    {
        this.busquedaListener = listener;
    }
    
    private void configurarHandlers() 
    {
        btnBuscar.addActionListener(e -> ejecutarBusqueda());
        txtPalabra.addActionListener(e -> ejecutarBusqueda()); // Enter en campo
    }
    
    private void ejecutarBusqueda() 
    {
        try 
        {
            String palabra = txtPalabra.getText();
            if (palabra == null || palabra.isBlank()) 
            {
                JOptionPane.showMessageDialog(this, "Ingrese un patron para buscar.");
                return;
            }
            if (busquedaListener != null) 
            {
                busquedaListener.onBuscar(palabra);
            }
            dispose();
        } 
        catch (Exception ex) 
        {
            JOptionPane.showMessageDialog(this, "Error en la busqueda: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPalabra = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Busqueda de Patrones");

        jPanel1.setPreferredSize(new java.awt.Dimension(525, 84));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText("Cadena a buscar:");
        jPanel1.add(jLabel1);

        txtPalabra.setColumns(20);
        jPanel1.add(txtPalabra);

        btnBuscar.setText("Buscar");
        jPanel1.add(btnBuscar);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtPalabra;
    // End of variables declaration//GEN-END:variables
}
